const LOCAL_KEY='health-os-local-v1';
let repoData={schemaVersion:1,daily:[],meals:[],workouts:[],bodyMetrics:[],inventory:[],mealPrep:[]};
let localData=JSON.parse(localStorage.getItem(LOCAL_KEY)||'{"daily":[],"meals":[],"workouts":[],"bodyMetrics":[],"inventory":[],"mealPrep":[]}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function merged(key){return [...(repoData[key]||[]),...(localData[key]||[])].sort((a,b)=>(a.date||'').localeCompare(b.date||''))}
function latestDaily(){const x=merged('daily');return x[x.length-1]||{}}
function val(v,s='—'){return v===0?0:(v??s)}
function saveLocal(){localStorage.setItem(LOCAL_KEY,JSON.stringify(localData));render()}
async function loadRepo(){try{const r=await fetch('data/store.json?ts='+Date.now());if(!r.ok)throw new Error();repoData=await r.json();$('#syncStatus').textContent='Repo data loaded';}catch{$('#syncStatus').textContent='Repo data unavailable · local mode';}render()}
function metric(label,value,unit=''){return `<div class="metric"><small>${label}</small><strong>${val(value)}${value!==undefined&&value!==null&&unit?' '+unit:''}</strong></div>`}
function renderToday(){const d=latestDaily();$('#todayMetrics').innerHTML=[
 metric('体重',d.body?.weightKg,'kg'),metric('步数',d.activity?.steps),metric('运动',d.activity?.exerciseMinutes,'min'),metric('摄入',d.nutrition?.calories,'kcal'),metric('蛋白质',d.nutrition?.proteinG,'g')
].join('')}
function lineChart(elId,rows,key,unit){const el=$(elId);const pts=rows.filter(r=>key(r)!=null).slice(-30);if(pts.length<2){el.innerHTML='<div class="empty">至少需要 2 天数据才能显示趋势。</div>';return}const w=600,h=190,p=24;const vals=pts.map(key),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const xy=pts.map((r,i)=>({x:p+i*(w-2*p)/(pts.length-1),y:h-p-(key(r)-min)*(h-2*p)/range,v:key(r),date:r.date}));const points=xy.map(q=>q.x+','+q.y).join(' ');const area=`${p},${h-p} ${points} ${w-p},${h-p}`;el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polygon class="chart-area" points="${area}"></polygon><polyline class="chart-line" points="${points}"></polyline>${xy.map(q=>`<circle class="chart-dot" cx="${q.x}" cy="${q.y}" r="3"><title>${q.date}: ${q.v} ${unit}</title></circle>`).join('')}<text class="axis-label" x="4" y="16">${Math.round(max*10)/10} ${unit}</text><text class="axis-label" x="4" y="${h-5}">${Math.round(min*10)/10} ${unit}</text></svg>`}
function renderCharts(){const d=merged('daily');lineChart('#weightChart',d,r=>r.body?.weightKg,'kg');lineChart('#calorieChart',d,r=>r.nutrition?.calories,'kcal')}
function renderDaily(){const rows=merged('daily').slice(-10).reverse();$('#dailyTable').innerHTML=rows.length?'<div class="data-row header"><span>日期</span><span>体重</span><span>步数</span><span>摄入</span><span>蛋白</span><span>运动</span></div>'+rows.map(r=>`<div class="data-row"><strong>${r.date}</strong><span>${val(r.body?.weightKg)} kg</span><span>${val(r.activity?.steps)}</span><span>${val(r.nutrition?.calories)} kcal</span><span>${val(r.nutrition?.proteinG)} g</span><span>${val(r.activity?.exerciseMinutes)} min</span></div>`).join(''):'<div class="empty">还没有每日数据。</div>'}
function renderNutrition(){const d=latestDaily();$('#nutritionMetrics').innerHTML=[metric('热量',d.nutrition?.calories,'kcal'),metric('蛋白质',d.nutrition?.proteinG,'g'),metric('碳水',d.nutrition?.carbsG,'g'),metric('脂肪',d.nutrition?.fatG,'g'),metric('餐次',merged('meals').filter(m=>m.date===d.date).length)].join('');const rows=merged('meals').slice(-12).reverse();$('#mealLog').innerHTML=rows.length?rows.map(m=>`<div class="list-row"><div><strong>${m.name}</strong><br><small>${m.date} · ${m.mealType||''}</small></div><span>${val(m.calories)} kcal</span><span>P ${val(m.proteinG)}g</span><span>C ${val(m.carbsG)} / F ${val(m.fatG)}</span></div>`).join(''):'<div class="empty">还没有饮食记录。</div>'}
function renderActivity(){const d=latestDaily();$('#activityMetrics').innerHTML=[metric('步数',d.activity?.steps),metric('运动',d.activity?.exerciseMinutes,'min'),metric('活动热量',d.activity?.activeCalories,'kcal'),metric('距离',d.activity?.distanceKm,'km'),metric('训练次数',merged('workouts').filter(w=>w.date===d.date).length)].join('');const rows=merged('workouts').slice(-12).reverse();$('#workoutLog').innerHTML=rows.length?rows.map(w=>`<div class="list-row"><div><strong>${w.type}</strong><br><small>${w.date}${w.notes?' · '+w.notes:''}</small></div><span>${val(w.durationMin)} min</span><span>${val(w.distanceKm)} km</span><span>HR ${val(w.avgHr)}</span></div>`).join(''):'<div class="empty">还没有运动记录。</div>'}
function renderBody(){const rows=[...merged('bodyMetrics'),...merged('daily').filter(x=>x.body).map(x=>({date:x.date,...x.body}))].sort((a,b)=>a.date.localeCompare(b.date));const b=rows[rows.length-1]||{};$('#bodyMetrics').innerHTML=[metric('体重',b.weightKg,'kg'),metric('体脂',b.bodyFatPct,'%'),metric('VO₂max',b.vo2max),metric('静息心率',b.restingHr,'bpm'),metric('睡眠',b.sleepHours,'h')].join('');$('#bodyLog').innerHTML=rows.length?rows.slice(-12).reverse().map(r=>`<div class="list-row"><strong>${r.date}</strong><span>${val(r.weightKg)} kg</span><span>VO₂ ${val(r.vo2max)}</span><span>RHR ${val(r.restingHr)}</span></div>`).join(''):'<div class="empty">还没有身体指标。</div>'}
function renderFood(){const inv=merged('inventory');$('#inventoryTable').innerHTML=inv.length?inv.map(i=>`<div class="list-row"><div><strong>${i.name}</strong><br><small>${i.expiryDate?'到期 '+i.expiryDate:'未记录到期日'}</small></div><span>${i.quantity} ${i.unit}</span><span>${val(i.kcalPer100g)} kcal/100g</span><span>P ${val(i.proteinPer100g)}g</span></div>`).join(''):'<div class="empty">还没有库存。</div>';const p=merged('mealPrep');$('#prepTable').innerHTML=p.length?p.map(x=>`<div class="list-row"><div><strong>${x.name}</strong><br><small>${x.date}</small></div><span>${x.servings} 份</span><span>${val(x.perServing?.calories)} kcal</span><span>P ${val(x.perServing?.proteinG)}g</span></div>`).join(''):'<div class="empty">还没有 Meal Prep。</div>'}
function render(){renderToday();renderCharts();renderDaily();renderNutrition();renderActivity();renderBody();renderFood()}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});
$$('[data-open]').forEach(b=>b.onclick=()=>{$('#'+b.dataset.open).showModal();const d=$('#'+b.dataset.open).querySelector('input[type=date]');if(d&&!d.value)d.value=today()});
$('#dailyForm').onsubmit=e=>{const f=new FormData(e.currentTarget);localData.daily.push({date:f.get('date'),body:{weightKg:n(f,'weight'),vo2max:n(f,'vo2max')},activity:{steps:n(f,'steps'),exerciseMinutes:n(f,'exerciseMinutes'),activeCalories:n(f,'activeCalories')},nutrition:{calories:n(f,'calories'),proteinG:n(f,'protein')},sleep:{hours:n(f,'sleepHours')}});saveLocal();toast('今日数据已保存到本机')};
$('#mealForm').onsubmit=e=>{const f=new FormData(e.currentTarget);localData.meals.push({id:crypto.randomUUID(),date:f.get('date'),mealType:f.get('mealType'),name:f.get('name'),calories:n(f,'calories'),proteinG:n(f,'protein'),carbsG:n(f,'carbs'),fatG:n(f,'fat')});saveLocal();toast('饮食已记录')};
$('#workoutForm').onsubmit=e=>{const f=new FormData(e.currentTarget);localData.workouts.push({id:crypto.randomUUID(),date:f.get('date'),type:f.get('type'),durationMin:n(f,'duration'),distanceKm:n(f,'distance'),avgHr:n(f,'avgHr'),notes:f.get('notes')});saveLocal();toast('运动已记录')};
$('#bodyForm').onsubmit=e=>{const f=new FormData(e.currentTarget);localData.bodyMetrics.push({date:f.get('date'),weightKg:n(f,'weight'),bodyFatPct:n(f,'bodyFat'),vo2max:n(f,'vo2max'),restingHr:n(f,'restingHr'),sleepHours:n(f,'sleepHours')});saveLocal();toast('身体指标已记录')};
$('#inventoryForm').onsubmit=e=>{const f=new FormData(e.currentTarget);localData.inventory.push({id:crypto.randomUUID(),name:f.get('name'),quantity:n(f,'quantity'),unit:f.get('unit'),expiryDate:f.get('expiryDate')||null,kcalPer100g:n(f,'kcal'),proteinPer100g:n(f,'protein')});saveLocal();toast('库存已添加')};
function n(f,k){const v=f.get(k);return v===''?null:Number(v)}
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(localData,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='health-os-local-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)};
loadRepo();